CREATE TABLE IF NOT EXISTS wallets (
    id VARCHAR(50) PRIMARY KEY,
    balance DECIMAL(18,4) NOT NULL CHECK (balance >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_wallets_id
ON wallets(id);


CREATE TABLE IF NOT EXISTS transfers (
    id VARCHAR(50) PRIMARY KEY,
    idempotency_key VARCHAR(100) UNIQUE NOT NULL,
    from_wallet_id VARCHAR(50) NOT NULL,
    to_wallet_id VARCHAR(50) NOT NULL,
    amount DECIMAL(18,4) NOT NULL CHECK (amount > 0),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_transfers_from_wallet
        FOREIGN KEY (from_wallet_id)
        REFERENCES wallets(id),

    CONSTRAINT fk_transfers_to_wallet
        FOREIGN KEY (to_wallet_id)
        REFERENCES wallets(id)
);

CREATE INDEX IF NOT EXISTS idx_transfers_id
ON transfers(id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_transfers_idempotency_key
ON transfers(idempotency_key);

CREATE INDEX IF NOT EXISTS idx_transfers_from_wallet
ON transfers(from_wallet_id);

CREATE INDEX IF NOT EXISTS idx_transfers_to_wallet
ON transfers(to_wallet_id);


CREATE TABLE IF NOT EXISTS ledger_entries (
    id VARCHAR(50) PRIMARY KEY,
    wallet_id VARCHAR(50) NOT NULL,
    transfer_id VARCHAR(50) NOT NULL,
    type VARCHAR(10) NOT NULL CHECK (type IN ('DEBIT', 'CREDIT')),
    amount DECIMAL(18,4) NOT NULL CHECK (amount > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_ledger_wallet
        FOREIGN KEY (wallet_id)
        REFERENCES wallets(id),

    CONSTRAINT fk_ledger_transfer
        FOREIGN KEY (transfer_id)
        REFERENCES transfers(id)
);

CREATE INDEX IF NOT EXISTS idx_ledger_entries_wallet_id
ON ledger_entries(wallet_id);

CREATE INDEX IF NOT EXISTS idx_ledger_entries_transfer_id
ON ledger_entries(transfer_id);


CREATE TABLE IF NOT EXISTS idempotency_records (
    idempotency_key VARCHAR(100) PRIMARY KEY,
    transfer_id VARCHAR(50),
    http_status INTEGER NOT NULL,
    response_body VARCHAR(5000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_idempotency_transfer
        FOREIGN KEY (transfer_id)
        REFERENCES transfers(id)
);


CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    wallet_id VARCHAR(50),

    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phoneno VARCHAR(15) NOT NULL,
    password VARCHAR(255) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_user_wallet
        FOREIGN KEY (wallet_id)
        REFERENCES wallets(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email
ON users(email);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phoneno
ON users(phoneno);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username
ON users(username);